### ISSUE TITLE
[Mod Interaction] Rats Can Burrow Into Thaumic Augmentation Warded Blocks

### ISSUE THREAD

**Issue by TechnoMysterio** [Alex-the-666/Rats#45]
Thaumic Augmentation, an addon for Thaumcraft, adds a focus effect that is a redesign of the old warding focus from earlier versions of Thaumcraft. When cast on a block, they become unbreakable by most means, especially with some upcoming changes that essentially make such blocks as tough as bedrock.

However, if you ward a block such as planks or dirt, which would still make said block completely unbreakable, rats are still able to burrow through them.

To test this I created a warding spell, made a small room with a chest in it, warded all blocks that surrounded the chest, placed some food in the chest and spawned a rat nearby. The rat was always able to burrow through the warded blocks to get to the food.

**Comment by TheCodex6824** [comment]
Hi, I'm the dev of Thaumic Augmentation, and I took a look into this from my end. On [this line](https://github.com/Alex-the-666/Rats/blob/master/src/main/java/com/github/alexthe666/rats/server/entity/EntityRat.java#L847) you check if the block hardness is less than a threshold. However, blocks that are unbreakable like bedrock have a hardness of -1.0 internally, so it passes that check. Since I emulate this value for warded blocks (and some blocks may have materials that require no tool to get their drops normally), rats end up digging into them.
