### ISSUE TITLE
plague doctor drinks potion to hide at night and fails conintuesly

### ISSUE THREAD

**Issue by whitequill** [Alex-the-666/Rats#485]
I'm having a problem where plague doctors are drinking their invisibility potion at night and then they don't vanish. They will then try and fail all night long!

I'm playing in All The Mods 6, Minecraft version 1.16.4
The traveling trader has the same problem.

**Comment by uecasm** [comment]
I have a similar but slightly different issue.  They drink the invisibility potion, successfully vanish, but then get annoyed they have a potion effect and drink milk to clear it... all night long.  This produces incredibly aggravating noises, especially since they pathfind as close to you as possible so they're always nearby if you're anywhere near the surface at night.

I'm playing in DW20 with mod version 7.0.1.

**Comment by BugmanBugman** [comment]
I believe this was a problem with Performant that got fixed
