### ISSUE TITLE
Rat won't defend owner (1.16)

### ISSUE THREAD

**Issue by Crowfooted** [Alex-the-666/Rats#486]
Using the battle-god upgrade I'm able to get my rat to behave normally with attacking animals or monsters in an area, but no matter what mode he is on he won't attack anything that attacks me, or anything that I attack. Have tried on Stay Here, Follow, Hunt Animals and Hunt Monsters.

**Comment by Tim2162286** [comment]
Same issue. I was able to get a rat with a ratinator upgrade to attack a player who attacked me if it was set to hunt monsters, but even that was sporadic. I'm on rats version 7.0.1-1.16.3, playing on the Direwolf20 1.16 pack.

**Comment by Nihilhalla** [comment]
This issue is still present in 7.2.0-1.16.5. I've had two players complain of rats not even defending themselves for that matter.
Rats in the "Follow me" pattern don't seem to defend the player who tamed them. Rats in the "Hunt Monsters" pattern seem to work for a period of time then sit there and die to mobs. Let me know what information would help you best, or if there's a debug setting I can enable so I can get you the data you need in order to fix this.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
