### ISSUE TITLE
1.12.2 rats wont wander

### ISSUE THREAD

**Issue by artzygal** [Alex-the-666/Rats#508]
please fix!

**Comment by luxidoptera** [comment]
Sorry to re-open this but it seems this issue was never fixed in any 1.12.2 versions. I am still experiencing this in MC Eternal, using the latest 1.12 version of Rats. Rats set to wander just...don't move. Ever. It's bizarre. 

I built such a nice cage for my rats and instead of running around and using it they just all sit together in one big glob of rodent :(

I totally understand if 1.12 is unsupported and thus this bug'll probably never be fixed but I figured I'd bump it on the off-chance that someone might be able to either fix it or tell me how to if it's an already-solved issue/one with a workaround
