### ISSUE TITLE
rats and ceramic buckets

### ISSUE THREAD

**Issue by benbenlaw** [Alex-the-666/Rats#519]
placing a milk clay bucket into cheese machine crashes the game
[crash-2021-01-10_12.11.01-server.txt](https://github.com/Alex-the-666/Rats/files/5792562/crash-2021-01-10_12.11.01-server.txt)

**Comment by cech12** [comment]
Yes this is an issue of this mod:

https://github.com/Alex-the-666/Rats/blob/1d5cdead8ba22b6d2e65141278154992b2f57274/src/main/java/com/github/alexthe666/rats/server/entity/tile/TileEntityAutoCurdler.java#L207

The `FluidUtil.getFluidHandler(ItemStack)` returns a `LazyOptional<IFluidHandlerItem>` instead of just an `IFluidHandlerItem` object.

**Comment by AlexModGuy** [comment]
fixed
