### ISSUE TITLE
Rats Won't move inside their cage

### ISSUE THREAD

**Issue by ewehewp** [Alex-the-666/Rats#644]
I left the rats on wander setting in their cage and they won't move

**Comment by Dr-Bone** [comment]
confirmed, same issue here. Rats won't move in cage, regardless of cage width or height. 
rats-7.1.1
mc 1.16.5

modpack: direwolf20

**Comment by C1ffisme** [comment]
I believe this has to do with the fact that mob AI is not designed to pathfind through blocks. I've noticed that while in rat cages, rats will jump up and down repeatedly while staying in the same place. You can observe similar behavior if you shove a rat in a bunch of glass blocks or put one in a cage made of trapdoors (recall that mobs view trapdoors as a solid block, making it ideal for mob traps):

![2021-09-18_15 56 06](https://user-images.githubusercontent.com/9893266/133908326-d46f68d0-f5cc-4bef-97a0-47d4813b5312.png)

The rat in this trapdoor cage will actually pathfind to cheese placed in the cage, but only after jumping around to get there first. For some reason, it's actually worse with a rat cage, in which they seem to be completely unable to move to any other cage block and may even be totally disinterested in cheese placed inside the cage. It seems like they also try to pathfind to the nearest air block, which is why I find them often looking towards the closest edge of the cage when I place them in.

**Comment by pkluver944** [comment]
This annoys me so much. What's the point of all the things to put in the rat cages if they can't properly use the cages!

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e
