### ISSUE TITLE
More rat hole variations

### ISSUE THREAD

**Issue by kihgy** [Alex-the-666/Rats#655]
More rat hole from vanilla and modded planks pls

**Comment by GizmoTheMoonPig** [comment]
if youre referring to the one in the creative tab, it only appears like that because oak planks is the default block facade the rat hole uses. The rat hole honestly shouldnt even be in the creative tab as its not meant to be used, theyre a block that replaces a normal vanilla block when a rat digs through them. You can, in theory, get a rat hole of any block just by setting the block entity data
