### ISSUE TITLE
How do I enable ratlantis on a 1.19.4 server?

### ISSUE THREAD

**Issue by SuperFirePanda** [Alex-the-666/Rats#798]
I see that you have to enable a datapack upon world creation. how would I do that on a server? And could I enable it while keeping our current progress?

**Comment by GizmoTheMoonPig** [comment]
To enable it, all you have to do is add `ratlantis` to `initial-enabled-packs` in the `server.properties` file. As far as I'm aware, you have to do this **BEFORE** generating a world due to how this property works. 

It doesn't look like there's a way to enable the pack on existing worlds. I tried messing with the `/datapack` command to enable it but it doesn't seem to like that. The pack says its enabled, however the dimension doesn't work, and it gets disabled when the world restarts. If I find a different workaround I'll post it here, but for now youll have to start a new world to use ratlantis stuff
