### ISSUE TITLE
Ratlantis Portal Overrides itself and moves

### ISSUE THREAD

**Issue by FirewallDaProtogen** [Alex-the-666/Rats#819]
[https://youtu.be/eikgUykh48Y](url)
i made a video showing the bug visually (theres also extra details in the desc)
the portal moves and overrides itself sometimes when going through it (from different sides, possibly?)

note: i would attach the video file directly but its a little too big

**Comment by GizmoTheMoonPig** [comment]
First off, I want to say thank you for the in-depth explanation of the issue in the video. Modders like myself greatly appreciate when people do this as it helps us figure out exactly what's happening a bit better. 
After I took up this project, one of the first things I did after porting the mod to 1.19.4 was redo Ratlantis entirely. This included how the portal generates. The portals now use a system similar to nether portals in that portals will properly link to each other.  The mod never used to do this; it would just write a portal if it didn't exist in the exact spot you teleported to. When you first teleported, you may be aware that you were stuck in a wall. This is actually where this issue came from, as the portal was checking that exact spot for the portal and not finding it! 
This video actually highlighted a second bug I also fixed: that portals would generate underground. They would sometimes generate really high in the air too, which doesn't make for a fun experience. Portals will now place directly above water or on top of the land/trees to allow for easier arrival and departure of the dimension. 
Unfortunately, I don't have the time nor motivation to continue supporting old versions of the mod. Considering the 1.19.4 port was essentially an entire backend rewrite of the mod, I would have to do a lot of work to bring it up to my current standards. Working a full-time job already cuts my time short, and I have 5 or 6 other projects to manage as well. Hopefully you'll consider playing 1.19.4 or 1.20 instead and enjoy the insane number of bugs that were fixed, as well as the new content I have already added, and more I have coming up very soon. 
Thank you again for the thorough documentation of the issue, it really helps us out!
