### ISSUE TITLE
1.19.4 Rats with fishing upgrade throwing items onto ground when they get a catch instead of putting them in a chest

### ISSUE THREAD

**Issue by CommandBlockGuru** [Alex-the-666/Rats#821]
I currently have 3 fishing rats in a modded survival I have. I've used the cheese wand to make them put their things in a chest when they catch stuff. It's on the block right next to them, they don't even have to move to put their things away. Their fishing spot is right next to said chest. Yet they just throw half the stuff they catch next to them.

Sometimes, things will get put in the chest, but most of the time when I come to check on them, there are fish and trash scattered around them instead of being put in the chest. I know they don't just toss em every time since there will sometimes be new stacks after a good while, but most of the time they still just throw them on the ground.

It's REALLY annoying and I don't think this ever happened in other versions of this since I usually set up fishing rats to get junk and a decent food source and they've never thrown their things, they've always carried it right to the chest. Dunno if older versions are still being updated but might as well try.

**Comment by GizmoTheMoonPig** [comment]
Currently rats will spawn the items on the ground after successfully fishing. Since I actually use the fishing loot tables with the changes mods make to them and all, sometimes rats will catch more than 1 thing while fishing. I can make the first stack get put directly into their hand but any others will HAVE to fall on the ground. 
Alternatively, I think it may be wise for me to change it so items get directly deposited into the chest if its close enough nearby. I might actually do this for a bunch of rat jobs as it would save a ton of processing power in terms of finding paths and whatnot. 
A way to get around this for now would just be to have another rat that collects items off the ground and deposit them all into a chest. I wont be updating 1.19.4 anymore as ive moved on to 1.20, but you can definitely expect to see this in 8.1.
