### ISSUE TITLE
Friends unable to join world in new update

### ISSUE THREAD

**Issue by SMHShark** [Alex-the-666/Rats#832]
After updating the mod my friends are unable to join they just get stuck on "Joining World"
1.20.1

**Comment by GizmoTheMoonPig** [comment]
do you have serene seasons and snowy spirit installed? If so i'll have a fix out that will resolve this.
If not, i'll need latest.log from one of your friends and the server

**Comment by SMHShark** [comment]
I don't have either of those mods and the latest.log is 55mbs big no site I upload it to will allow the whole log

**Comment by SMHShark** [comment]
Unless you know of a way to send it idk how else I could
missclick close oops

**Comment by GizmoTheMoonPig** [comment]
you can just upload the file here to github, I dont mind downloading it

**Comment by HeavyDeception** [comment]
@SMHShark you can copy and paste your log here https://mclo.gs/ then copy the page link and it will share you log.

**Comment by SMHShark** [comment]
[latest.zip](https://github.com/AlexModGuy/Rats/files/12886803/latest.zip)

Github doesn't allow files bigger than 25mbs and even mclo didn't like it either idk what's up with this log but zipping it got it small enough to post here. Sorry for the confusion and the wait.

**Comment by GizmoTheMoonPig** [comment]
alright this is a super strange issue. Looks like when im caching the mobs for the mob filter, Mooshrooms are throwing an error because someone is injecting a data accessor into cows. I think it may be [[Lets Do] Meadow](https://www.curseforge.com/minecraft/mc-mods/welcome-to-meadow) that's causing the issue. Can you try removing that and get back to me about it? If thats the problem I can look into this further, otherwise we'll keep looking. 
If that isnt the problem mod send me another latest.log after removing the mod so I can look again

**Comment by abundzu** [comment]
Experienced similar issue as described by OP (log overflowing at login) and removing meadow resolved it. 

Edit: bit further testing, didn't crash with just rats + meadow for me, also required Suspicious Zombification to replicate crash. Removing any one of the three seems to allow world to load.

**Comment by GizmoTheMoonPig** [comment]
ok thats very good to know, thank you! I'll see whats causing the issue since its been narrowed to those 2 mods

**Comment by SMHShark** [comment]
@GizmoTheMoonPig Can also confirm removing meadow with my modlist works. I don't have Suspicious Zombification so let me know whenever you're able to fix it! Thanks.

**Comment by GizmoTheMoonPig** [comment]
alright I did some more testing and I'm fairly sure this is an issue with meadow and how they add variants to mobs. If any mod adds a mob that extends the vanilla cow, chicken, or sheep class and they add data accessors this issue will show up. I have no way of preventing this from my end as far as I'm aware, but I did change it so the game will properly crash when opening the mob filter instead of hanging on login. 
I would let the people who work on meadow know this is an issue. I don't know a better way to inject data accessors into mobs, but the way they're doing it doesn't work properly. Feel free to link them back to this issue!

**Comment by GizmoTheMoonPig** [comment]
8.1.2 will no longer hang the game on login, but be warned that if you open the mob filter with meadow still installed it will crash. This is not something I can fix, meadow is unsafely adding data to mobs 
(I meant to reply to this a few days ago but got busy. My bad!)
