### ISSUE TITLE
MobGriefing 

### ISSUE THREAD

**Issue by DragonBlade77** [Alex-the-666/Rats#892]
Not necessarily a bug or anything, but rat's harvesting functions do not work properly with mob griefing disabled, and there is no way to make them do so on the 1.20.1 Forge version of the mod (as gamerule config mods are not available for that version). 

Having mobgriefing disabled is really important for a server I am currently running, and unfortunately rats are not interacting well because of it. They pretty much just stare at the selected block at the moment. 

A look at this issue would be greatly appreciated!

**Comment by GizmoTheMoonPig** [comment]
this is intentional, as rats can do destructive actions I feel that having them follow mob griefing is a must. Villagers also completely break if mob griefing is disabled too! 
If you want finer control of what mobs can be destructive I recommend using this mod: https://www.curseforge.com/minecraft/mc-mods/more-mobgriefing-options. I will not be changing how rats follow the gamerule
